version: '3.1'
services:
  mysql:
    image: mysql:5.7
    container_name: prisma-mysql
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - $DB_PORT:3306